### PR TITLE
Unlock jsoo >= 4.0.0 and sedlex >= 2.4

### PR DESCRIPTION
**Pull request by kit-ty-kate**
not sure what's up with those either (see similar PR on virtual_dom and async_js)

### CODE REVIEW

**Comment by tov** [comment]
Does this work on 5.0.0~alpha1 for you?

**Comment by kit-ty-kate** [comment]
Yes, if you have https://github.com/kit-ty-kate/opam-alpha-repository/

**Comment by tov** [comment]
Do I have to do something to get it to use that besides `opam repo add alpha git+https://github.com/kit-ty-kate/opam-alpha-repository.git` followed by `opam update` and `opam upgrade`? Because it doesn't seem to be picking up the versions there. For example, if I run `opam list js_of_ocaml` it shows me up through `js_of_ocaml.4.0.0` but not `js_of_ocaml.4.0.0.1~alpha-repo`.

**Comment by kit-ty-kate** [comment]
are you sure you're in the right switch? By default `opam repo add` adds to the current switch, not all of them. Also note that `opam update` and `opam upgrade` are not needed after a `opam repo add`

**Comment by tov** [comment]
Oh, thanks, that might be it. I didn't realize that repositories were per-switch, but that makes sense.

**Pull request merged**
